name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py2app
      - name: Build macOS App
        run: python setup.py py2app
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: TeacherPlanner.app
          path: dist/TeacherPlanner.app
